version: "2"
services:
  web:
      image: nginx
      volumes:
        - ./services/config/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8080:80"
      environment:
        - NGINX_HOST=foobar.com
        - NGINX_PORT=80
      links:
        - "php"

  db:
      image: mysql
      ports:
        - "3336:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=defaultpass

  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    volumes:
      - ./package:/mnt/app

  console:
    build:
      context: ./services/console
      dockerfile: Dockerfile
    links:
      - php
    volumes:
      - ./package:/mnt/app
    tty: true

  ndbman:
    container_name: management_env1
    image: "mysql/mysql-cluster"
    entrypoint: /entrypoint.sh ndb_mgmd
    ports:
        - "3308:3306"
    volumes:
        - ./services/mysql/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=defaultpass
    networks:
      php_network:
        ipv4_address: 192.168.0.2

  datanode1:
    container_name: ndb_env1
    image: "mysql/mysql-cluster"
    entrypoint: /entrypoint.sh ndbd
    ports:
            - "13306:3306"
    volumes:
       - ./services/mysql/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=defaultpass
    networks:
      php_network:
        ipv4_address: 192.168.0.3

  mysqld:
    container_name: mysql_env
    image: "mysql/mysql-cluster"
    entrypoint: /entrypoint.sh mysqld
    ports:
      - "3306:3306"
    volumes:
       - ./services/mysql/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=defaultpass
    networks:
      php_network:
        ipv4_address: 192.168.0.10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: "db"
      PMA_USER: "root"
      PMA_PASSWORD: "defaultpass"

networks:
  php_network:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.0.0/16