version: "2"
services:
  web:
      image: nginx
      volumes:
        - ./services/config/default.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8080:80"
      environment:
        - NGINX_HOST=foobar.com
        - NGINX_PORT=80
      links:
        - "php"

  php:
    build:
      context: ./services/php
      dockerfile: Dockerfile
    volumes:
      - ./package:/mnt/app

  console:
    build:
      context: ./services/console
      dockerfile: Dockerfile
    links:
      - php
    volumes:
      - ./package:/mnt/app
    tty: true

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: "192.168.99.100"
      PMA_USER: "root"
      PMA_PASSWORD: "defaultpass"